server:
  port: 8080
spring:
  redis:
    #redis数据库索引(默认为0)
    database: 0
    #redis服务器地址
    host: 39.108.218.95
    #redis服务器连接端口
    port: 6379
    #redis连接密码
    password:
    #redis连接池设置
    pool:
      #最大空闲连接
      max-idle: 100
      #最小空闲连接
      min-idle: 1
      #最大连接数(负数表示没有限制)
      max-active: 1000
      #最大阻塞等待时间(负数表示没有限制)
      max-wait: -1
      #连接超时时间(毫秒)
      timeout: 0
  datasource:
    username: root
    password: root  #修改为自己的数据库密码
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT

mybatis:
  # 指定全局配置文件位置
#  config-location: classpath:mybatis/mybatis-config.xml
  # 指定sql映射文件位置
  mapper-locations: classpath:mapper/*.xml

logging:
  # 在当前磁盘的根路径下创建spring文件夹和里面的log文件夹;
  #使用 spring.log 作为默认文件;
  #当file和path同时使用时,以file为准
  #  在控制台输出的日志的格式
  pattern:
    console: '%d{yyyy-MM-dd} [%thread] %-5level %logger{50} - %msg%n'
    # 指定文件中日志输出的格式
    file: '%d{yyyy-MM-dd} === [%thread] === %-5level === %logger{50} === - %msg%n'
  file:
    name: springboot.log
  #文件上传相关设置
  servlet:
    multipart:
      max-file-size: 10Mb
      max-request-size: 100Mb
  #devtools插件
  devtools:
    livereload:
      enabled: true #是否支持livereload
      port: 35729
    restart:
      enabled: true #是否支持热部署